name: Output Information
on: workflow_dispatch
jobs: 
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub Context
              run: |
                echo "Repository: ${{ toJSON(github) }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Event Name: ${{ github.event_name }}"
                echo "Actor: ${{ github.actor }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"